import { type CreateEraserOptions, type CreateImageOptions, type CreateSceneOptions, type CreateShapeOptions, type CreateStrokeOptions, type CreateTextOptions, type DrawingHistory, type EraserElement, type HistoryAction, type ImageElement, type Scene, type SceneElement, type SceneOperation, type ShapeElement, type StrokeElement, type TextElement } from "./types.js";
export declare const HISTORY_LIMIT = 100;
export declare function createScene(options?: CreateSceneOptions): Scene;
export declare function createStrokeElement(options: CreateStrokeOptions): StrokeElement;
export declare function createEraserElement(options: CreateEraserOptions): EraserElement;
export declare function createShapeElement(options: CreateShapeOptions): ShapeElement;
export declare function createTextElement(options: CreateTextOptions): TextElement;
export declare function createImageElement(options: CreateImageOptions): ImageElement;
export declare function cloneElement(element: SceneElement): SceneElement;
export declare function cloneScene(scene: Scene): Scene;
export declare function assertElement(value: unknown, label?: string): asserts value is SceneElement;
export declare function assertScene(value: unknown): asserts value is Scene;
export declare function serializeScene(scene: Scene): string;
export declare function migrateScene(value: unknown): Scene;
export declare function deserializeScene(serialized: string): Scene;
export declare function applySceneOperation(scene: Scene, operation: SceneOperation): Scene;
export declare function createHistory(scene: Scene): DrawingHistory;
export declare function historyReducer(history: DrawingHistory, action: HistoryAction): DrawingHistory;
export declare function sceneStrokes(scene: Scene): readonly StrokeElement[];
export declare function sceneEraserOperations(scene: Scene): readonly EraserElement[];
